global:
  storageClass:
  imagePullSecrets: []

secretsManager:
  bankVault:
    enabled: false
    ## Banzaicloud bank-vaults mutating webhook annotations
    ## https://banzaicloud.com/docs/bank-vaults/mutating-webhook/annotations/
    annotations:
      vault.security.banzaicloud.io/vault-addr: "https://vault:8200"

nameOverride:
fullnameOverride:

image:
  repository:
  tag:
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  create: false
  name:
  annotations: {}
  automountServiceAccountToken: true

revisionHistoryLimit: 5

terminationGracePeriodSeconds: 60

containerPort: 8080

## @param extraContainerPorts - Extra ports to expose in the container
## extraContainerPorts:
##   - name: http
##     containerPort: 9090
##     protocol: TCP
extraContainerPorts:

service:
  type: ClusterIP
  targetPort: 8080
  port: 8080

  ## @param service.extraPorts - Extra ports to expose in the service (normally used with the `sidecar` value)
  ##
  extraPorts:

ingress:
  enabled: false
  certManager: false
  annotations: {}
    # kubernetes.io/ingress.class: ingress

  path: / # Default path for extraHosts

  hosts:
    - host: common.example.com
      paths:
        - /
  #tls:
  #  - secretName: tls-secret-name
  #    hosts:
  #      - common.example.com

  ## @param ingress.pathType - Ingress Path type
  ##
  pathType: ImplementationSpecific

  ## @param ingress.extraHosts - The list of additional hostnames to be covered with this ingress record.
  ## extraHosts:
  ## - name: test2.example.com
  ##   path: /
  ##
  extraHosts: []

  ## @param ingress.extraTls - The tls configuration for additional hostnames to be covered with this ingress record.
  ## extraTls:
  ## - hosts:
  ##     - test2.example.com
  ##   secretName: tls-secret-name-2
  ##
  extraTls: []

  ## @param ingress.ingressClassName IngressClass that will be be used to implement the Ingress (Kubernetes 1.18+)
  ingressClassName:

livenessProbe: {}
readinessProbe: {}

resources: {}
#  limits:
#    cpu: 200m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: []

tolerations: []

affinity: {}

## @param env - Array containing env vars to configure service
##
## Default envs example:
## env:
##   - name: DATABASE_URL
##     value: "mysql://127.0.0.1:3306"
##   - name: LOG_LEVEL
##     value: "debug"
##
## Secrets from Vault example:
## env
##   - name: DB_PASSWORD
##     value: "vault:secrets/data/database#DB_PASSWORD"
##   - name: AUTH_TOKEN
##     value: "vault:secrets/data/example#AUTH_TOKEN"
##
env:

## @param configMapFile - Filename or matching wildcard pattern
## For example:
## configMapFile: "application.yml"
## 
## or multiple files:
## configMapFile: "**.json"
##
## Before using this param, you need to COPY all files into "config/" chart directory
##
## For example in CI/CD:
## cp src/main/resources/application.yml common-app-chart/config/
##
## or multiple files:
## cp src/main/resources/*.json common-app-chart/config/
## 
configMapFile:

## @param extraVolumes - Array to add extra volumes. Requires setting `extraVolumeMounts`
## For example:
## extraVolumes:
##   - name: assets
##     persistentVolumeClaim:
##       claimName: assets-pvc
extraVolumes:

## @param extraVolumeMounts - Array to add extra mounts. Normally used with `extraVolumes`
## For example:
## extraVolumeMounts:
##   - name: assets
##     mountPath: /tmp/assets
extraVolumeMounts:

## @param hostAliases - Add deployment host aliases
##
hostAliases: []

## @param updateStrategy.type - Set up update strategy for deploy.
## Example:
## updateStrategy:
##   type: RollingUpdate
##   rollingUpdate:
##     maxSurge: 25%
##     maxUnavailable: 25%
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

## @param sidecars - Attach additional containers to the pod
## e.g.
## - name: your-image-name
##   image: your-image
##   imagePullPolicy: Always
##   ports:
##   - name: portname
##     containerPort: 1234
##
sidecars:

## @param initContainers - Add additional init containers to the pod
## e.g.
## - name: your-image-name
##   image: your-image
##   imagePullPolicy: Always
##   ports:
##   - name: portname
##     containerPort: 1234
##
initContainers:

## Autoscaling parameters
## @param autoscaling.enabled Enable autoscaling for app deployment
## @param autoscaling.minReplicas Minimum number of replicas to scale back
## @param autoscaling.maxReplicas Maximum number of replicas to scale out
## @param autoscaling.targetCPU Target CPU utilization percentage
## @param autoscaling.targetMemory Target Memory utilization percentage
##
autoscaling:
  enabled: false
  minReplicas: ""
  maxReplicas: ""
  targetCPU: ""
  targetMemory: ""

## @param kubeVersion Force target Kubernetes version (using Helm capabilities if not set)
##
kubeVersion:

