{{- if .Values.configMapFile }}
{{- $configPath := printf "%s/%s" "config" .Values.configMapFile -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-config
  namespace: {{ .Release.namespace }}
  labels: {{- include "service.labels.standard" . | nindent 4 }}
data: {{- (tpl (.Files.Glob $configPath).AsConfig . ) | nindent 2 }}
{{- end }}