
{{- if .Values.virtualService.enabled }}
apiVersion: {{ include "capabilities.virtualservice.apiVersion" .}}
kind: VirtualService
metadata:
  name: {{ include "service.fullname" . }}-vsa
  namespace: {{ .Release.namespace }}
spec:
  gateways:
  - istio-system/istio-ingress-gateway
  {{- range .Values.virtualService.hosts }}
  hosts:
  - {{ .host }}
  http:
  - match:
    - uri:
      {{- range .prefix }}
        prefix: {{ . }}
      {{- end }}
  {{- end }}
    name: primary
    route:
    - weight: 0
      {{- include "virtualService.destination" (dict "serviceName" (include "service.fullname" $) "subsetName" "stable" "context" $)  | nindent 6 }}
{{- end }}
